#!/usr/bin/env python3
import sqlite3
id = 0;
temperature = 0.0;
date = '2020-10-05';

dbconnect = sqlite3.connect("my.db");

dbconnect.row_factory = sqlite3.Row;

cursor = dbconnect.cursor();
for i in range(10):
    id += 1;
    temperature += 1.1;
    cursor.execute('''insert into temperature values (?, ?, ?)''',
    (id, temperature, date));
dbconnect.commit();

cursor.execute('SELECT * FROM temperature');

for row in cursor:
    print(row['id'],row['temp'],row['date'] );

dbconnect.close();
